### ISSUE TITLE
Include soft-links in data object `__repr__`

### ISSUE THREAD

**Issue by maxhutch** [CitrineInformatics/taurus#15]
When using jupyter, the representation of the object shown in the output cell is its `__repr__`.  By default, that only shows object members, which excludes soft links.  This leads to the non-obvious behavior that `repr(process_run)` doesn't include ingredients and `repr(material_run)` doesn't include measurements.

We should override `__repr__` in objects that include soft-links to show linked objects.

h/t @sesevgen

**Comment by maxhutch** [comment]
The work around is to print the soft-linked return value, e.g. `print(process_run.ingredients)`

**Comment by bfolie** [comment]
Resolved with #26
