### ISSUE TITLE
Change "unique_label" to "name"

### ISSUE THREAD

**Issue by bfolie** [CitrineInformatics/taurus#3]
IngredientSpec and IngredientRun have a "unique_label" field, and ProcessTemplate has a "allowed_unique_label" field. Per the most recent docs, those should be changed to "name" and "allowed_names".

This raises questions about the HasLabels mix-in trait, which ensures that "labels" is a list of strings and "unique_label" is a string. Is it necessary to make this a separate trait? If ingredients now have a "name" field that is being used for searching the same way "name" is used for other objects, should "name" be validated as a string in the case of other objects as well?

**Comment by maxhutch** [comment]
Closed in https://github.com/CitrineInformatics/taurus/pull/8
