### ISSUE TITLE
PropertiesAndConditions sounds like there are multiple properties.

### ISSUE THREAD

**Issue by gregor-robinson** [CitrineInformatics/taurus#72]
I suggest we rename `PropertiesAndConditions` to `PropertyWithConditions`.

**Comment by kroenlein** [comment]
The object is defined to be `PropertyAndConditions` (singular on the first term).  Your concern still stands?

**Comment by gregor-robinson** [comment]
Ah, excellent. Just the documentation did the plural. I opened PR https://github.com/CitrineInformatics/taurus-documentation/pull/24 and I'll close this issue.
